In [5]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [6]:
# load data
data = sm.datasets.get_rdataset("Guerry", "HistData").data
data.head()

,dept,Region,Department,Crime_pers,Crime_prop,Literacy,Donations,Infants,Suicides,MainCity,...,Crime_parents,Infanticide,Donation_clergy,Lottery,Desertion,Instruction,Prostitutes,Distance,Area,Pop1831
0,1,E,Ain,28870,15890,37,5098,33120,35039,2:Med,...,71,60,69,41,55,46,13,218.372,5762,346.03
1,2,N,Aisne,26226,5521,51,8901,14572,12831,2:Med,...,4,82,36,38,82,24,327,65.945,7369,513.00
2,3,C,Allier,26747,7925,13,10973,17044,114121,2:Med,...,46,42,76,66,16,85,34,161.927,7340,298.26
3,4,E,Basses-Alpes,12935,7289,46,2733,23018,14238,1:Sm,...,70,12,37,80,32,29,2,351.399,6925,155.90
4,5,E,Hautes-Alpes,17488,8174,69,6962,23076,16171,1:Sm,...,22,23,64,79,35,7,1,320.280,5549,129.10

In [7]:
data.columns

Index(['dept', 'Region', 'Department', 'Crime_pers', 'Crime_prop', 'Literacy',
       'Donations', 'Infants', 'Suicides', 'MainCity', 'Wealth', 'Commerce',
       'Clergy', 'Crime_parents', 'Infanticide', 'Donation_clergy', 'Lottery',
       'Desertion', 'Instruction', 'Prostitutes', 'Distance', 'Area',
       'Pop1831'],
      dtype='object')

In [8]:
# Fit OLS regression use ln
res = smf.ols("Lottery ~ Literacy + np.log(Pop1831)", data=data).fit()
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                Lottery   R-squared:                       0.348
Model:                            OLS   Adj. R-squared:                  0.333
Method:                 Least Squares   F-statistic:                     22.20
Date:                Sun, 25 Feb 2024   Prob (F-statistic):           1.90e-08
Time:                        16:25:07   Log-Likelihood:                -379.82
No. Observations:                  86   AIC:                             765.6
Df Residuals:                      83   BIC:                             773.0
Df Model:                           2
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept         246.4341     35.233      6.995      0.000     176.358     316.510
Literacy           -0.4889      0.128     -3.832      0.000      -0.743      -0.235
np.log(Pop1831)   -31.3114      5.977     -5.239      0.000     -43.199     -19.424
==============================================================================
Omnibus:                        3.713   Durbin-Watson:                   2.019
Prob(Omnibus):                  0.156   Jarque-Bera (JB):                3.394
Skew:                          -0.487   Prob(JB):                        0.183
Kurtosis:                       3.003   Cond. No.                         702.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [19]:
# Using numpy arrays
# Definir el nÃºmero de observaciones
nobs = 100

# Generar datos aleatorios X con dimensiones (nobs, 2) utilizando numpy.random.random
X = np.random.random((nobs, 2))

# Agregar una columna de unos a los datos X utilizando sm.add_constant para ajustar un intercepto en el modelo
X = sm.add_constant(X)

# Definir los coeficientes beta del modelo como [1, .1, 0.5]
beta = [1, .1, 0.5]

# Generar errores aleatorios de longitud nobs utilizando numpy.random.random
e = np.random.random(nobs)

# Generar datos de respuesta y utilizando el modelo lineal y = X * beta + e
y = np.dot(X, beta) + e

# Ajustar un modelo de mÃ­nimos cuadrados ordinarios (OLS) utilizando los datos generados
# y y X utilizando sm.OLS().fit()
res_2 = sm.OLS(y, X).fit()

# Imprimir un resumen del ajuste del modelo
print(res_2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.344
Model:                            OLS   Adj. R-squared:                  0.330
Method:                 Least Squares   F-statistic:                     25.40
Date:                Sun, 25 Feb 2024   Prob (F-statistic):           1.34e-09
Time:                        16:35:07   Log-Likelihood:                -7.1161
No. Observations:                 100   AIC:                             20.23
Df Residuals:                      97   BIC:                             28.05
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.4416      0.067     21.497      0.000       1.308       1.575
x1             0.0354      0.096      0.368      0.714      -0.156       0.226
x2             0.6721      0.096      7.005      0.000       0.482       0.863
==============================================================================
Omnibus:                        3.536   Durbin-Watson:                   2.437
Prob(Omnibus):                  0.171   Jarque-Bera (JB):                2.074
Skew:                          -0.080   Prob(JB):                        0.355
Kurtosis:                       2.313   Cond. No.                         5.10
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [9]:
dir(res)

['HC0_se',
 'HC1_se',
 'HC2_se',
 'HC3_se',
 '_HCCM',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abat_diagonal',
 '_cache',
 '_data_attr',
 '_data_in_cache',
 '_get_robustcov_results',
 '_get_wald_nonlinear',
 '_is_nested',
 '_transform_predict_exog',
 '_use_t',
 '_wexog_singular_values',
 'aic',
 'bic',
 'bse',
 'centered_tss',
 'compare_f_test',
 'compare_lm_test',
 'compare_lr_test',
 'condition_number',
 'conf_int',
 'conf_int_el',
 'cov_HC0',
 'cov_HC1',
 'cov_HC2',
 'cov_HC3',
 'cov_kwds',
 'cov_params',
 'cov_type',
 'df_model',
 'df_resid',
 'diagn',
 'eigenvals',
 'el_test',
 'ess',
 'f_pvalue',
 'f_test',
 'fittedvalues',
 'fvalue',
 'get_influence',
 'get_prediction',
 'get_robustcov_results',
 'info_criteria',
 'initialize',
 'k_constant',
 'llf',
 'load',
 'model',
 'mse_model',
 'mse_resid',
 'mse_total',
 'nobs',
 'normalized_cov_params',
 'outlier_test',
 'params',
 'predict',
 'pvalues',
 'remove_data',
 'resid',
 'resid_pearson',
 'rsquared',
 'rsquared_adj',
 'save',
 'scale',
 'ssr',
 'summary',
 'summary2',
 't_test',
 't_test_pairwise',
 'tvalues',
 'uncentered_tss',
 'use_t',
 'wald_test',
 'wald_test_terms',
 'wresid']

In [10]:
from patsy import dmatrix

In [11]:
data.columns

Index(['dept', 'Region', 'Department', 'Crime_pers', 'Crime_prop', 'Literacy',
       'Donations', 'Infants', 'Suicides', 'MainCity', 'Wealth', 'Commerce',
       'Clergy', 'Crime_parents', 'Infanticide', 'Donation_clergy', 'Lottery',
       'Desertion', 'Instruction', 'Prostitutes', 'Distance', 'Area',
       'Pop1831'],
      dtype='object')

In [12]:
vars = ['Department', 'Lottery', 'Literacy', 'Wealth' ,'Region']

In [13]:
df = data[vars].copy()
df.dropna()
df.head()

     Department  Lottery  Literacy  Wealth Region
0           Ain       41        37      73      E
1         Aisne       38        51      22      N
2        Allier       66        13      61      C
3  Basses-Alpes       80        46      76      E
4  Hautes-Alpes       79        69      83      E

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Department  86 non-null     object
 1   Lottery     86 non-null     int64
 2   Literacy    86 non-null     int64
 3   Wealth      86 non-null     int64
 4   Region      85 non-null     object
dtypes: int64(3), object(2)
memory usage: 3.5+ KB